### ISSUE TITLE
Don't handle requestexception

### ISSUE THREAD

**Issue by Ravencentric** [aritsulynn/anipie#1]
First, thanks for this library. Came in clutch right when I needed it. It's great!

While I was testing, I fed some wrong data and wrote my own exception handler and was surprised to find out the library handles it itself and prints it. This has a few issues in that I can't handle the exception the way I want to.

https://github.com/aritsulynn/anipie/blob/3d35394f8559c8222edb86b8061a47276a12f81d/anipie/search_by_query.py#L27-L34

My proposed solution is to either raise a custom exception or just remove the try catch so the requestexception propagates to the library user (me) and then I can handle it according to my own needs

**Comment by aritsulynn** [comment]
Thanks for reporting the issue! I've made a change to search_by_query.py (lines 35-36) that should prevent the error you encountered.

https://github.com/aritsulynn/anipie/blob/3640c97b228d3c0c7c256464c0499a8592910e62/anipie/search_by_query.py#L35C9-L36C21

**Comment by Ravencentric** [comment]
this still has the same issue, you shouldn't return it but simply let it raise

**Comment by aritsulynn** [comment]
[#3 ](https://github.com/aritsulynn/anipie/blob/fd3cd64b488b99764ea2a2566dd4ed3e37606af9/anipie/search_by_query.py#L38C1-L45C38) We got update here to handle the error

**Comment by Ravencentric** [comment]
That works! Thank you!
